# Generated by Django 4.2.4 on 2023-09-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranker',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
