# Generated by Django 4.2.4 on 2023-09-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacman', '0002_ranker_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranker',
            options={'managed': False},
        ),
    ]
